const menu = [
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.99,
        img: 'https://www.momontimeout.com/wp-content/uploads/2016/04/pancakes-recipe-buttermilk-733x487.jpg',
        desc: ` a pancake made with buttermilk. battercake, flannel cake, flannel-cake, flapcake, flapjack, hot cake, hotcake, pancake, griddlecake - a flat cake of thin batter fried on both sides on a griddle.`,
    },
    {
        id: 2,
        title: 'diner double',
        category: 'lunch',
        price: 13.99,
        img: 'https://www.dennys.ca/wp-content/uploads/2019/10/images-1.jpg',
        desc: `Canada's Diner Double Cheeseburger. Canadian cheese, caramelized onions and All-Canadian sauce on a brioche bun. Served with wavy-cut French fries.`,
    },
    {
        id: 3,
        title: 'godzilla milkshake',
        category: 'drinks',
        price: 6.99,
        img: 'https://d3hkrbfxf7jd3r.cloudfront.net/article/lead_image/6371095/0_DSC_5334-copy-1.jpg',
        desc: `Milo Godzilla Milkshake - the topseller! Milo blended with banana & mint chocolate chip ice cream, drizzled with melted chocolate.`,
    },
    {
        id: 4,
        title: 'country delight',
        category: 'breakfast',
        price: 20.99,
        img: 'https://dbijapkm3o6fj.cloudfront.net/resources/19434,1004,1,6,4,0,600,450/-4601-/20190201222234/breakfast-delight-buffet.jpeg',
        desc: `Barley breakfast delight is a nice change of pace in the hot cereal arena, made with honey, pear nectar, cinnamon, and dried cranberries.`,
    },
    {
        id: 5,
        title: 'grilled chicken salad',
        category: 'lunch',
        price: 22.99,
        img: 'https://www.ecoliteracy.org/sites/default/files/styles/hero_image_small/public/media/rethinking-school-lunch-guide.jpg?itok=JFKW4vOU&timestamp=1490386525',
        desc: `Simply include a few protein-rich elements in your diet, such as poultry, lean meats, and fish with low-fat foods to get a proper balance.`,
    },
    {
        id: 6,
        title: 'oreo dream',
        category: 'breakfast',
        price: 18.99,
        img: 'https://www.365daysofbakingandmore.com/wp-content/uploads/2014/05/Oreo-Pudding-Dream-Bars-FEATURE.jpg',
        desc: `Tantalize your taste-buds to this creamy, delish Heavenly Oreo Cookie Cream Layered Dessert! It's sooooo amazing and only has 8 ingredients!`,
    },
    {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: 'https://media-cdn.tripadvisor.com/media/photo-s/03/db/a8/e4/annie-s-overflow.jpg',
        desc: `Overflow Bacon. Covered tomato sauce, Swiss cheese sauce, basil sauce, cheese and smoked bacon.`,
    },
    {
        id: 8,
        title: 'american classic',
        category: 'lunch',
        price: 12.99,
        img: 'https://assets.bonappetit.com/photos/57ad3da553e63daf11a4dd3f/1:1/w_800%2Cc_limit/Diner41.jpg',
        desc: `Change up the burger toppings according to the season: lettuce and pickled onions in winter months; sliced tomato and housemade bread-and-butter pickles in the summer.`,
    },
    {
        id: 9,
        title: 'quarantine buddy',
        category: 'drinks',
        price: 16.99,
        img: 'https://res.cloudinary.com/purnesh/image/upload/w_540,f_auto/header-8-places-in.jpg',
        desc: `For the uninitiated, they are milkshakes topped with cream, topped with cake, topped with sauce, with a handful of sweets thrown in for good measure – a monstrous mashup of a drink and dessert.`,
    },
    {
        id: 10,
        title: 'chicken-fried steak',
        category: 'lunch',
        price: 21.99,
        img: 'https://assets.bonappetit.com/photos/57ace204f1c801a1038bc881/1:1/w_800%2Cc_limit/chicken-fried-steak.jpg',
        desc: `This hot-weather version of a comfort food classic is paired with a fresh, no-cook salsa. Looks like gravy, tastes like summer.`,
    },
    {
        id: 11,
        title: 'sour cherry pie',
        category: 'breakfast',
        price: 5.99,
        img: 'https://assets.bonappetit.com/photos/57ad43b21b3340441497558b/1:1/w_800%2Cc_limit/sour-cherry-pie.jpg',
        desc: `Adding almond flour to the pastry dough makes for a super-tender, toasty-looking crust.`,
    },
    {
        id: 12,
        title: 'perfect porterhouse steak',
        category: 'lunch',
        price: 30.00,
        img: 'https://assets.bonappetit.com/photos/57ad5452f1c801a1038bcb97/1:1/w_800%2Cc_limit/perfect-porterhouse-steak.jpg',
        desc: `With a steak this thick, you need to season liberally; when chef Bobby Flay demonstrated for us, the surface of the meat was virtually white from salt.`,
    },
    {
        id: 13,
        title: 'coffee',
        category: 'drinks',
        price: 9.99,
        img: 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_500740897_200013331653767347294_333325.jpg',
        desc: `
        Coffee - Wikipediahttps://en.wikipedia.org › wiki › Coffee
        Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain Coffea species.`,
    },
    {
        id: 14,
        title: 'orange juice',
        category: 'drinks',
        price: 5.99,
        img: 'https://static.toiimg.com/photo/msid-68562297/68562297.jpg?950123',
        desc: `Orange juice is a liquid extract of the orange tree fruit, produced by squeezing or reaming oranges. `,
    },
    {
        id: 15,
        title: 'orange juice',
        category: 'drinks',
        price: 7.99,
        img: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F19%2F2016%2F04%2F29%2Fsummer-sweet-lemonade-cl-2000.jpg',
        desc: `The acid in lemonade stimulates salivation, making you feel hydrated. A heat wave has many people in the eastern United States reaching for cold beverages such as lemonade and citrus-flavored soda.`,
    },
];
export default menu;
